import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="max-w-screen-md mx-auto p-4">
          <header style={{ background:"#09f",color:"#fff"}}>
            <h1>Next.jsサンプル</h1>
            <nav>
              <a href="/">Home</a> | <a href="/about">About</a> | <a href="/login">Login</a> | <a href="/register">Register</a>
            </nav>
          </header>
          {children}
          <footer>
            <p style={{ background:"#eef",padding:"10px",textAlign:"center"}}>2025</p>
          </footer>
        </main>
      </body>
    </html>
  );
}
